from __future__ import annotations

import time
from pathlib import Path
from typing import Any, Literal

import gymnasium as gym
from gymnasium import spaces
import mujoco
import mujoco.viewer
import numpy as np

from reach_touch_inspire_demo import (
    DEFAULT_MODEL,
    POINTING_HAND,
    REST_ARM,
    TOUCH_ARM,
    InspireReachTouchDemo,
)


RenderMode = Literal["human"]


class InspireReachEnv(gym.Env[np.ndarray, np.ndarray]):
    """Continuous-control fingertip reaching task for Actor-Critic training.

    The hand remains in the validated pointing pose. The policy controls four
    left-arm joints with bounded joint-position increments. Each target is
    generated by forward kinematics from a randomly sampled reachable pose.

    Observation (19 values):
        q[4], qdot[4], fingertip_xyz[3], target_xyz[3],
        target_minus_fingertip[3], distance[1], hold_progress[1]

    Action (4 values in [-1, 1]):
        normalized increments for shoulder pitch, shoulder roll,
        shoulder yaw, and elbow.
    """

    metadata = {"render_modes": ["human"], "render_fps": 30}

    CONTROLLED_ARM_INDICES = np.array([0, 1, 2, 3], dtype=np.int64)
    TARGET_POSE_LOW = np.array([-1.35, 0.12, -0.28, 0.90])
    TARGET_POSE_HIGH = np.array([-0.72, 0.48, 0.28, 1.48])

    def __init__(
        self,
        model_path: str | Path = DEFAULT_MODEL,
        render_mode: RenderMode | None = None,
        maximum_episode_steps: int = 120,
        action_scale: float = 0.055,
        control_dt: float = 0.04,
        success_tolerance: float = 0.045,
        required_success_steps: int = 8,
        target_visual_radius: float = 0.018,
    ) -> None:
        super().__init__()
        if render_mode not in {None, "human"}:
            raise ValueError("render_mode must be None or 'human'")
        if maximum_episode_steps <= 0:
            raise ValueError("maximum_episode_steps must be positive")
        if action_scale <= 0 or control_dt <= 0:
            raise ValueError("action_scale and control_dt must be positive")
        if success_tolerance <= 0 or required_success_steps <= 0:
            raise ValueError("success settings must be positive")

        self.render_mode = render_mode
        self.maximum_episode_steps = maximum_episode_steps
        self.action_scale = float(action_scale)
        self.control_dt = float(control_dt)
        self.success_tolerance = float(success_tolerance)
        self.required_success_steps = int(required_success_steps)

        self.demo = InspireReachTouchDemo(
            Path(model_path), success_tolerance, target_visual_radius
        )
        self.model = self.demo.model
        self.data = self.demo.data
        self.controlled = [
            self.demo.arm_ids[index]
            for index in self.CONTROLLED_ARM_INDICES
        ]
        self.joint_low = np.array(
            [self.model.jnt_range[self._joint_id(qpos_id), 0]
             for qpos_id, _, _ in self.controlled],
            dtype=np.float64,
        )
        self.joint_high = np.array(
            [self.model.jnt_range[self._joint_id(qpos_id), 1]
             for qpos_id, _, _ in self.controlled],
            dtype=np.float64,
        )

        self.action_space = spaces.Box(-1.0, 1.0, shape=(4,), dtype=np.float32)
        float_limit = np.finfo(np.float32).max
        self.observation_space = spaces.Box(
            -float_limit, float_limit, shape=(19,), dtype=np.float32
        )

        self.arm_pose = REST_ARM.copy()
        self.target_pose = TOUCH_ARM.copy()
        self.target_position = np.zeros(3, dtype=np.float64)
        self.previous_distance = 0.0
        self.episode_step = 0
        self.success_streak = 0
        self.viewer = None

    def _joint_id(self, qpos_id: int) -> int:
        matches = np.flatnonzero(self.model.jnt_qposadr == qpos_id)
        if len(matches) != 1:
            raise RuntimeError(f"Cannot resolve joint for qpos index {qpos_id}")
        return int(matches[0])

    def _set_pose(self, arm_pose: np.ndarray, qvel: np.ndarray | None = None) -> None:
        self.demo.apply_control(arm_pose, POINTING_HAND)
        for index, (_, qvel_id, _) in enumerate(self.controlled):
            self.data.qvel[qvel_id] = 0.0 if qvel is None else qvel[index]
        mujoco.mj_forward(self.model, self.data)

    def _sample_target_pose(self) -> np.ndarray:
        pose = TOUCH_ARM.copy()
        pose[self.CONTROLLED_ARM_INDICES] = self.np_random.uniform(
            self.TARGET_POSE_LOW, self.TARGET_POSE_HIGH
        )
        return pose

    def _observation(self) -> np.ndarray:
        q = np.array([self.data.qpos[item[0]] for item in self.controlled])
        qdot = np.array([self.data.qvel[item[1]] for item in self.controlled])
        tip = self.demo.fingertip_position()
        delta = self.target_position - tip
        distance = float(np.linalg.norm(delta))
        hold_progress = min(1.0, self.success_streak / self.required_success_steps)
        return np.concatenate(
            [q, qdot, tip, self.target_position, delta, [distance, hold_progress]]
        ).astype(np.float32)

    def _info(self) -> dict[str, Any]:
        tip = self.demo.fingertip_position()
        distance = float(np.linalg.norm(self.target_position - tip))
        return {
            "distance": distance,
            "fingertip_position": tip.copy(),
            "target_position": self.target_position.copy(),
            "target_pose": self.target_pose.copy(),
            "arm_pose": self.arm_pose.copy(),
            "success_streak": self.success_streak,
            "episode_step": self.episode_step,
            "is_success": self.success_streak >= self.required_success_steps,
        }

    def reset(
        self,
        *,
        seed: int | None = None,
        options: dict[str, Any] | None = None,
    ) -> tuple[np.ndarray, dict[str, Any]]:
        super().reset(seed=seed)
        self.demo.reset()
        self.arm_pose = REST_ARM.copy()
        self._set_pose(self.arm_pose)

        if options is not None and "target_pose" in options:
            target_values = np.asarray(options["target_pose"], dtype=np.float64)
            if target_values.shape == (4,):
                self.target_pose = TOUCH_ARM.copy()
                self.target_pose[self.CONTROLLED_ARM_INDICES] = target_values
            elif target_values.shape == REST_ARM.shape:
                self.target_pose = target_values.copy()
            else:
                raise ValueError("target_pose must contain 4 or 7 joint values")
        else:
            self.target_pose = self._sample_target_pose()

        self.target_position = self.demo._position_for_pose(
            self.target_pose, POINTING_HAND
        )
        self.demo.target_position = self.target_position.copy()
        self._set_pose(self.arm_pose)
        self.previous_distance = float(
            np.linalg.norm(self.target_position - self.demo.fingertip_position())
        )
        self.episode_step = 0
        self.success_streak = 0
        if self.render_mode == "human":
            self.render()
        return self._observation(), self._info()

    def step(
        self, action: np.ndarray
    ) -> tuple[np.ndarray, float, bool, bool, dict[str, Any]]:
        action = np.asarray(action, dtype=np.float64)
        if action.shape != (4,) or not np.isfinite(action).all():
            raise ValueError("action must be a finite four-element vector")
        clipped_action = np.clip(action, -1.0, 1.0)
        old_q = self.arm_pose[self.CONTROLLED_ARM_INDICES].copy()
        new_q = np.clip(
            old_q + self.action_scale * clipped_action,
            self.joint_low,
            self.joint_high,
        )
        self.arm_pose[self.CONTROLLED_ARM_INDICES] = new_q
        self._set_pose(self.arm_pose, (new_q - old_q) / self.control_dt)
        self.data.time += self.control_dt
        self.episode_step += 1

        distance = float(
            np.linalg.norm(self.target_position - self.demo.fingertip_position())
        )
        progress = self.previous_distance - distance
        touched = distance <= self.success_tolerance
        self.success_streak = self.success_streak + 1 if touched else 0
        terminated = self.success_streak >= self.required_success_steps
        truncated = self.episode_step >= self.maximum_episode_steps

        reward = 25.0 * progress - 1.5 * distance
        reward -= 0.01 * float(np.square(clipped_action).sum())
        if touched:
            reward += 0.5
        if terminated:
            reward += 10.0
        self.previous_distance = distance

        if self.render_mode == "human":
            self.render()
        return self._observation(), float(reward), terminated, truncated, self._info()

    def render(self) -> None:
        if self.render_mode != "human":
            return
        if self.viewer is None:
            self.viewer = mujoco.viewer.launch_passive(self.model, self.data)
            self.viewer.cam.lookat[:] = np.array([0.05, 0.05, 0.9])
            self.viewer.cam.distance = 2.2
            self.viewer.cam.azimuth = 150.0
            self.viewer.cam.elevation = -10.0
        if self.viewer.is_running():
            touched = self.previous_distance <= self.success_tolerance
            self.demo.add_target_to_viewer(self.viewer, touched)
            self.viewer.sync()
            time.sleep(1.0 / self.metadata["render_fps"])

    def close(self) -> None:
        if self.viewer is not None:
            self.viewer.close()
            self.viewer = None

